{{- if dig "serviceAccount" "create" false .Values.AsMap }}
{{- $name := dig "serviceAccount" "name" "" .Values.AsMap -}}
{{- if empty $name }}
  {{- fail "serviceAccount.name must be defined when serviceAccount.create is true" }}
{{- end }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  {{- with dig "serviceAccount" "annotations" dict .Values.AsMap }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "rqlite.labels" . | nindent 4 }}
{{- end }}
